/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frotter;

import java.awt.Color;

/**
 *
 * @author ANDRÉ
 */
public class Criar_Conta extends javax.swing.JFrame {

    /**
     * Creates new form Criar_Conta
     */
    public Criar_Conta() {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(890, 540));
        setMinimumSize(new java.awt.Dimension(890, 540));
        setSize(new java.awt.Dimension(890, 540));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA DE NASCIMENTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 170, 140, 10);

        jTextField1.setBackground(new java.awt.Color(190, 193, 255));
        jTextField1.setText("***************");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(430, 310, 190, 30);

        jLabel3.setText("CONFIRMAR PALAVRA-PASSE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 290, 170, 10);

        jTextField2.setBackground(new java.awt.Color(190, 193, 255));
        jTextField2.setText("*************");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 310, 190, 30);

        jButton1.setBackground(new java.awt.Color(255, 40, 40));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1bnt_Enter(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 370, 190, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/9025316_car_icon (2).png"))); // NOI18N
        jLabel2.setText("FROTTER");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 168, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DE USUARIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 230, 120, 10);

        jTextField3.setBackground(new java.awt.Color(190, 193, 255));
        jTextField3.setText("00/00/0000");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 190, 190, 30);

        jLabel6.setText("PALAVRA-PASSE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 290, 110, 10);

        jTextField4.setBackground(new java.awt.Color(190, 193, 255));
        jTextField4.setText("*************");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 370, 190, 30);

        jTextField5.setBackground(new java.awt.Color(190, 193, 255));
        jTextField5.setText("exemplo.isptec@gmail.com");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(430, 130, 190, 30);

        jTextField6.setBackground(new java.awt.Color(190, 193, 255));
        jTextField6.setText("exemplo.isptec@gmail.com");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(210, 130, 190, 30);

        jTextField7.setBackground(new java.awt.Color(190, 193, 255));
        jTextField7.setText("RDC");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(430, 190, 190, 30);

        jTextField8.setBackground(new java.awt.Color(190, 193, 255));
        jTextField8.setText("exemplo.isptec@gmail.com");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(430, 250, 190, 30);

        jLabel10.setText("E-MAIL");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 110, 50, 10);

        jLabel11.setText("PAÍS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 170, 50, 10);

        jLabel9.setText("NOME");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 110, 50, 10);

        jLabel12.setText("PROVINCIA");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 230, 80, 10);

        jComboBox1.setBackground(new java.awt.Color(190, 193, 255));
        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTORISTA" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 250, 190, 30);

        jLabel7.setText("Nº DE CARTA DE CONDUÇÃO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 350, 160, 10);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/Rectangle 6.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 90, 460, 340);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(890, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 540));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 540);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/background.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(890, 540));
        jLabel5.setMinimumSize(new java.awt.Dimension(890, 540));
        jLabel5.setPreferredSize(new java.awt.Dimension(890, 540));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 890, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1bnt_Enter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1bnt_Enter
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1bnt_Enter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criar_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criar_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criar_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criar_Conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Criar_Conta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
