/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frotter;

import java.awt.Color;

/**
 *
 * @author ANDRÉ
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       jPanel1.setBackground(new Color(0,0,0,200));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(890, 540));
        setMinimumSize(new java.awt.Dimension(890, 540));
        setSize(new java.awt.Dimension(890, 540));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-MAIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 110, 50, 20);

        jTextField2.setBackground(new java.awt.Color(190, 193, 255));
        jTextField2.setText("*************");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 210, 190, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REGISTAR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 330, 70, 16);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("__________");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 330, 80, 16);

        jTextField1.setBackground(new java.awt.Color(190, 193, 255));
        jTextField1.setText("exemplo.isptec@gmail.com");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 140, 190, 30);

        jLabel3.setText("SENHA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 180, 50, 20);

        jButton1.setBackground(new java.awt.Color(255, 40, 40));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_Enter(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 290, 190, 30);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Lembrar-se de mim");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(290, 250, 170, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/Rectangle 6.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 90, 310, 300);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/9025316_car_icon (2).png"))); // NOI18N
        jLabel2.setText("FROTTER");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 168, 40);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(890, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(890, 540));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 510);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/background.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(890, 540));
        jLabel5.setMinimumSize(new java.awt.Dimension(890, 540));
        jLabel5.setPreferredSize(new java.awt.Dimension(890, 540));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 820, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_Enter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_Enter
        // TODO add your handling code here:
    }//GEN-LAST:event_bnt_Enter

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
